### ISSUE TITLE
Grue prevents Minecraft from starting

### ISSUE THREAD

**Issue by thekirbykid20067** [Shinoow/Grue#19]
#### Description:

Minecraft won't start with Grue installed.

#### Crash report:

https://paste.dimdev.org/uluguhunib.mccrash

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft:1.12.2
- Forge:14.23.5.2847
- Grue:1.5.0

**Comment by Shinoow** [comment]
You have an invalid value inside "Dynamic Lights List" in the Grue config.
I would need to see what values you've inserted into that list to determine which one is invalid, but it is whichever isn't using the format `modid:name`.

**Comment by thekirbykid20067** [comment]
Yeah, I had it set to just "torch". Thanks.
