### ISSUE TITLE
[Suggesttion] Grue compatible with optifine's dynamic lights

### ISSUE THREAD

**Issue by Managarmr719** [Shinoow/Grue#2]
It would be great if Grue was compatible with Optifine's implementation of dynamic lights just like it is with AtomicStryker's Dynamic Lights mod. I normally would use AtomicStryker's version but I will already be using Optifine so I would have to use a second mod that does fundamentally the same because the first doesn't work well with Grue. It's not a major issue but it's a bit annoying. :\

**Comment by Shinoow** [comment]
If there was a way to interact with Optifine (or just a simple way to tell if the Dynamic Lights in it was enabled), there would already be compatibility. But since Optifine isn't a Forge mod, and it possibly making direct edits to the settings screen (no idea if there would be a way to access Optifine's settings through vanilla's), there's a big chance I would have to go through a lot of extra stuff just to dig this info out for a single check.

**Comment by Managarmr719** [comment]
Ok, that's a shame. I guess I will just have to use both. Thanks anyway :).

**Comment by QuImUfu** [comment]
Maybe @sp614x could provide a way to get the information needed to make Grue compatible with optifine's dynamic lights?

**Comment by sp614x** [comment]
What kind of interaction is needed?
Via reflection you can call `Config.isDynamicLights()` or access `GameSettings.ofDynamicLights`.

**Comment by Shinoow** [comment]
What I need is a simple check if dynamic lights is installed (while OF is present and the config option for it in Grue is enabled). It'll be a call during the EntityJoinWorldEvent, so all I really need is to check if the dynamic light is enabled (while OF is present).

**Comment by Seth0067** [comment]
Hey this may be dumb - but how about just checking if the player has a torch in current or off-hand?

**Comment by Adarcer** [comment]
from what i Noticed optifine dynamic lights do not change the light level of the area... but they do let you see. use your light level overlay and you can plainly see the difference between the two mods.. optifine produces less light lag due too this feature..

**Comment by FlopD0g** [comment]
You can do this by going into darknesslib's config file and changing Dynamic Lights Mode to true
