### ISSUE TITLE
"Sunken" blocks like soul sand cause grue to spawn regardless of light level

### ISSUE THREAD

**Issue by RedHerring26** [Shinoow/Grue#20]
Description:

When the player walks over a block that causes them to sink down a small amount, the light level gets read as zero, causing a grue to spawn. This can be observed with soul sand when only the grue mod is installed, but it occurs with modded blocks that behave similarly as well.

Crash report:

N/A

----

Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Grue: 1.5.0

**Comment by Equeon** [comment]
Seconded, observed with Mud from Biomes o' Plenty.
