### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by MidnightBree** [Shinoow/Grue#23]
An option to remove Grue spawning in water would be really nice.  When simply swimming on the surface during the night, I get him spawning behind me as I swim.  Grue doesn't even chase either.  It just floats there until daylight.

#### Crash Report: N/A

----

#### Affected versions ("latest" is **NOT** a version):
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.5.2847
- Grue: 1.6.0

**Comment by Shinoow** [comment]
They're actually not supposed to spawn in water unless it's exactly one block deep. Seems like I've made an oversight on that.
