### ISSUE TITLE
[Suggestion] MobStage or GameStage support for Grue Mod

### ISSUE THREAD

**Issue by RisingInIris2017** [Shinoow/Grue#24]
#### Description:
I would like to make new players not to run into Grues when they still do not have enough torches to prevent themselves from being in dark places. So I tried to use [MobStage Mod](https://github.com/Darkhax-Minecraft/MobStages) to replace Grue with less dangerous mob, but I have failed. 
I have tested with Grue-1.12.2-1.7.0 that I cannot replace or disable Grue's generation by MobStages-1.12.2-2.0.8, which is the latest version of MobStage when I write this issue.

#### Tested versions:
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Grue: 1.12.2-1.7.0
- GameStage: GameStages-1.12.2-2.0.115
- MobStage: 1.12.2-2.0.8

#### Suggestion:
My suggestion is making a MobStage or GameStage integration, which helps modpack makers to control Grues's generation. You may decide how to program it, just choose a easiest way.
Look forward to your reply.
Thanks in advance!

**Comment by Shinoow** [comment]
I can probably whip up something similar to what I did in Hungering Darkness. You'd basically specify stages where the Grue doesn't spawn, then stages where it does, where each stage is given a priority that determines the outcome (eg. if the current highest priority stage is in the group for not spawning, the Grue act on that player).

**Comment by RisingInIris2017** [comment]
> You'd basically specify stages where the Grue doesn't spawn, then stages where it does, where each stage is given a priority that determines the outcome (eg. if the current highest priority stage is in the group for not spawning, the Grue act on that player).

I have made a Zenscript like this:
<pre>
mods.MobStages.addStage("furnace", "grue:entitygrue");
mods.MobStages.addRange("grue:entitygrue", 16);
mods.MobStages.addReplacement("grue:entitygrue", "minecraft:cave_spider");
</pre>
Then save and test it in game, but Grue still spawn near me, even though I have no GameStage specified.
This script is correct, since replacing `"grue:entitygrue"` with vanilla mobs' ID will replace that mob with cave spider.
I have difficulties in understanding the method you mentioned in your comment. Would you like to explain it more?
Thanks in advance

**Comment by Shinoow** [comment]
What I'm describing wouldn't be done through any Zenscript, it'll be an array of Strings in the config that would then be used if Game Stages is present.
Mob Stages won't work on Grue do to the way they spawn, which doesn't get picked up by the events it checks for.

**Comment by RisingInIris2017** [comment]
> it'll be an array of Strings in the config that would then be used if Game Stages is present.

Oh, I have got it. 
I have not found that config entry in Grue-1.12.2-1.7.0's config file. Do you mean that you will add this config entry in the next version of Grue Mod?

**Comment by RisingInIris2017** [comment]
Thanks for your effort! 🎉
