### ISSUE TITLE
Cipher

### ISSUE THREAD

**Issue by ggilost** [Shinoow/Grue#25]
No actual problem, I am sending this ticket to find out which cypher did you use(if it isn't just gibberish) for when the grue possesses you, just asking no urgency.

**Comment by Shinoow** [comment]
By cipher, do you mean the sounds? Because those are all gibberish I've recorded.

**Comment by ggilost** [comment]
No no, this might be from a different mod that ties in with the grue but this is the thing I'm talking about.
![cipher](https://user-images.githubusercontent.com/60539157/89818578-d208d800-db6b-11ea-8cd7-95c077e58f4d.png)

**Comment by Shinoow** [comment]
Yeah, that's not part of Grue.

**Comment by ggilost** [comment]
Oh okay, thank you for your time, wouldn't mind a lead tho, if you don't want to that is fine as well just close this thread.

**Comment by Shinoow** [comment]
Based on that screenshot I can't make a guess on anything. I've never seen a mod write out that much gibberish in the chat window (judging by the lack of a single reoccurring "word" from a few glances of it, I don't think that's a cipher).
