### ISSUE TITLE
[Request] Underground/height limit for the grue

### ISSUE THREAD

**Issue by charlesbevans** [Shinoow/Grue#4]
I forgot about the grue being able to spawn under trees at night and got eaten while building a base on a slime island... I think the grues stuck to caves and the underground. Could you please add a configuration to limit the Y-level or check for sky access before spawning the grue. (I don't want to add In Control just for the grue.)

**Comment by Shinoow** [comment]
This problem was handled in 1.3.5, with the brightness calculations also checking the skylight, thus stopping any spawning below trees.
