### ISSUE TITLE
[Suggestion] 2 Wimp mode suggestions

### ISSUE THREAD

**Issue by scribbler957** [Shinoow/Grue#7]
1. Set a numerical value for wimp mode, so grues can be tough, without being insta-death.
2. Set a wimp mode dimension list. I'd like to see weaker grue in the overworld with stronger grue in dimensions like deep dark and beneath.

1+2 Set a value per dimension. (I've been toying with using world drop to make players go through increasingly deep dimensions to reach the nether. Increasingly dangerous grue would be cool.)

**Comment by charlesbevans** [comment]
Make that 3. An option to link wimp mode to the light level so that the grue scales from DOA in 0 light to wet noodle in 15 daylight.

**Comment by Mike-U5** [comment]
Very much agree with suggestion #1.
